steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:latest'
      - './backend'
    id: 'build-backend'

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/frontend:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/frontend:latest'
      - './frontend'
    id: 'build-frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}'
    id: 'push-backend'

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/frontend:${SHORT_SHA}'
    id: 'push-frontend'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_BACKEND_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/backend:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},JWT_SECRET_KEY=${_JWT_SECRET_KEY},GITHUB_CLIENT_ID=${_GITHUB_CLIENT_ID},GITHUB_CLIENT_SECRET=${_GITHUB_CLIENT_SECRET},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET},FRONTEND_URL=${_FRONTEND_URL},OPENAI_API_KEY=${_OPENAI_API_KEY},STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY},STRIPE_PRICE_ID_BASIC=${_STRIPE_PRICE_ID_BASIC},STRIPE_PRICE_ID_PRO=${_STRIPE_PRICE_ID_PRO},ADMIN_API_KEY=${_ADMIN_API_KEY},ADMIN_PASSWORD=${_ADMIN_PASSWORD},SMTP_SERVER=${_SMTP_SERVER},SMTP_PORT=${_SMTP_PORT},SMTP_USERNAME=${_SMTP_USERNAME},SMTP_PASSWORD=${_SMTP_PASSWORD},FROM_EMAIL=${_FROM_EMAIL},SUPPORT_EMAIL=${_SUPPORT_EMAIL},FREE_SCAN_LIMIT=${_FREE_SCAN_LIMIT}'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_FRONTEND_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/frontend:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

substitutions:
  _REGION: us-central1
  _REPO_NAME: vulnerability-scanner
  _BACKEND_SERVICE_NAME: vulnerability-scanner-backend
  _FRONTEND_SERVICE_NAME: vulnerability-scanner-frontend
  _FRONTEND_URL: https://vulnerability-scanner-frontend-xxxxx.run.app
  _DATABASE_URL: ''
  _JWT_SECRET_KEY: ''
  _GITHUB_CLIENT_ID: ''
  _GITHUB_CLIENT_SECRET: ''
  _GOOGLE_CLIENT_ID: ''
  _GOOGLE_CLIENT_SECRET: ''
  _OPENAI_API_KEY: ''
  _STRIPE_SECRET_KEY: ''
  _STRIPE_PRICE_ID_BASIC: ''
  _STRIPE_PRICE_ID_PRO: ''
  _ADMIN_API_KEY: ''
  _ADMIN_PASSWORD: ''
  _SMTP_SERVER: smtp.gmail.com
  _SMTP_PORT: '587'
  _SMTP_USERNAME: ''
  _SMTP_PASSWORD: ''
  _FROM_EMAIL: ''
  _SUPPORT_EMAIL: support@daifend.com
  _FREE_SCAN_LIMIT: '5'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'

